import type { Card, EnergyType, GameData } from "./types";

export const MAX_POINTS = 3;
export const MAX_BENCH = 3;
export const MAX_HAND = 10;
export const OPENING_HAND = 5;
export const WEAKNESS_BONUS = 20;

export const energyImages: Record<EnergyType, string> = {
  grass: "/assets/energy/grass-energy.png",
  fire: "/assets/energy/fire-energy.png",
  water: "/assets/energy/water-energy.png",
  lightning: "/assets/energy/lightning-energy.png",
  psychic: "/assets/energy/psychic-energy.png",
  fighting: "/assets/energy/fighting-energy.png",
  darkness: "/assets/energy/darkness-energy.png",
  metal: "/assets/energy/steel-energy.png",
};

export const cards: Record<string, Card> = {
  matikanetannhauserBasic: {
    id: "matikanetannhauserBasic",
    owner: "player",
    kind: "pokemon",
    name: "Matikanetannhauser",
    label: "Umamusume - Psychic - Basic",
    species: "Matikanetannhauser",
    type: "Psychic",
    stage: 0,
    hp: 60,
    portrait: "/assets/umamusume/matikanetannhauser-basic.png",
    weakness: { type: "Darkness", amount: WEAKNESS_BONUS },
    retreat: "Colorless",
    attacks: [{ name: "Nosebleed", cost: { psychic: 1 }, damage: 20, text: "Do 20 damage to the active Umamusume." }],
  },
  matikanetannhauserStage1: {
    id: "matikanetannhauserStage1",
    owner: "player",
    kind: "pokemon",
    name: "Matikanetannhauser",
    label: "Umamusume - Psychic - Stage 1",
    species: "Matikanetannhauser",
    type: "Psychic",
    stage: 1,
    evolvesFrom: "Matikanetannhauser",
    hp: 100,
    portrait: "/assets/umamusume/matikanetannhauser-stage1.png",
    weakness: { type: "Darkness", amount: WEAKNESS_BONUS },
    retreat: "Colorless x2",
    attacks: [{ name: "Bad Luck, Dispel!", cost: { psychic: 2 }, damage: 40, coinBonus: 20, text: "Flip a coin. If heads, do +20 damage." }],
  },
  matikanetannhauserStage2: {
    id: "matikanetannhauserStage2",
    owner: "player",
    kind: "pokemon",
    name: "Matikanetannhauser",
    label: "Umamusume - Psychic - Stage 2",
    species: "Matikanetannhauser",
    type: "Psychic",
    stage: 2,
    evolvesFrom: "Matikanetannhauser",
    hp: 150,
    portrait: "/assets/umamusume/matikanetannhauser-stage2.png",
    weakness: { type: "Darkness", amount: WEAKNESS_BONUS },
    retreat: "Colorless x2",
    ability: { name: "Ei, Ei, Mun!", text: "Heal 20 HP at the start of your turn.", heal: 20 },
    attacks: [{ name: "Wasshoi Mambo!", cost: { psychic: 2, colorless: 1 }, damage: 70, coinBonus: 30, text: "Flip a coin. If heads, do +30 damage." }],
  },
  niceNatureBasic: {
    id: "niceNatureBasic",
    owner: "player",
    kind: "pokemon",
    name: "Nice Nature",
    label: "Umamusume - Grass - Basic",
    species: "Nice Nature",
    type: "Grass",
    stage: 0,
    hp: 70,
    portrait: "/assets/umamusume/nice-nature-basic.png",
    weakness: { type: "Fire", amount: WEAKNESS_BONUS },
    retreat: "Colorless",
    ability: { name: "Supporting Star", text: "Your active Umamusume gets +10 HP.", activeHpBonus: 10 },
    attacks: [{ name: "Third Again?!", cost: { grass: 1, colorless: 1 }, damage: 40, text: "Do 40 damage to the active Umamusume." }],
  },
  nishinoFlowerBasic: {
    id: "nishinoFlowerBasic",
    owner: "player",
    kind: "pokemon",
    name: "Nishino Flower",
    label: "Umamusume - Grass - Basic",
    species: "Nishino Flower",
    type: "Grass",
    stage: 0,
    hp: 70,
    portrait: "/assets/umamusume/nishino-flower-basic.png",
    weakness: { type: "Fire", amount: WEAKNESS_BONUS },
    retreat: "Colorless",
    attacks: [{ name: "Budding Blossom", cost: { grass: 1 }, damage: 20, heal: 10, healTarget: "any", text: "Heal 10 damage from one of your Umamusume." }],
  },
  mihonoBourbonBasic: {
    id: "mihonoBourbonBasic",
    owner: "player",
    kind: "pokemon",
    name: "Mihono Bourbon",
    label: "Umamusume - Metal - Basic",
    species: "Mihono Bourbon",
    type: "Metal",
    stage: 0,
    hp: 50,
    portrait: "/assets/umamusume/mihono-bourbon-basic.png",
    weakness: { type: "Fighting", amount: WEAKNESS_BONUS },
    retreat: "Colorless",
    ability: { name: "Cyborg Armor", text: "This Umamusume takes 10 less damage from attacks from your opponent's active Umamusume.", damageReduction: 10 },
    attacks: [{ name: "Reflect", cost: { metal: 1 }, damage: 0, preventDamageNextTurn: 10, text: "Take 10 less damage from attacks from your opponent's active Umamusume next turn." }],
  },
  mihonoBourbonStage1: {
    id: "mihonoBourbonStage1",
    owner: "player",
    kind: "pokemon",
    name: "Mihono Bourbon",
    label: "Umamusume - Metal - Stage 1",
    species: "Mihono Bourbon",
    type: "Metal",
    stage: 1,
    evolvesFrom: "Mihono Bourbon",
    hp: 70,
    portrait: "/assets/umamusume/mihono-bourbon-stage1.png",
    weakness: { type: "Fighting", amount: WEAKNESS_BONUS },
    retreat: "Colorless x2",
    ability: { name: "Cyborg Armor", text: "This Umamusume takes 10 less damage from attacks from your opponent's active Umamusume.", damageReduction: 10 },
    attacks: [{ name: "Mirror Shot", cost: { metal: 1, colorless: 1 }, damage: 40, bonusIfTookDamageLastTurn: 10, text: "If this Umamusume took damage last turn, this attack does +10 damage." }],
  },
  mihonoBourbonStage2: {
    id: "mihonoBourbonStage2",
    owner: "player",
    kind: "pokemon",
    name: "Mihono Bourbon",
    label: "Umamusume - Metal - Stage 2",
    species: "Mihono Bourbon",
    type: "Metal",
    stage: 2,
    evolvesFrom: "Mihono Bourbon",
    hp: 130,
    portrait: "/assets/umamusume/mihono-bourbon-stage2.png",
    weakness: { type: "Fighting", amount: WEAKNESS_BONUS },
    retreat: "Colorless x3",
    ability: { name: "Cyborg Armor", text: "This Umamusume takes 10 less damage from attacks from your opponent's active Umamusume.", damageReduction: 10 },
    attacks: [{ name: "G00 1st. F∞", cost: { metal: 2, colorless: 1 }, damage: 60, preventDamageNextTurn: 10, bonusIfTookDamageLastTurn: 10, text: "Take 10 less damage next turn. If this Umamusume took damage last turn, this attack does +10 damage." }],
  },
  haruUraraBasic: {
    id: "haruUraraBasic",
    owner: "player",
    kind: "pokemon",
    name: "Haru Urara",
    label: "Umamusume - Psychic - Basic",
    species: "Haru Urara",
    type: "Psychic",
    stage: 0,
    hp: 80,
    portrait: "/assets/umamusume/haru-urara-basic.png",
    weakness: { type: "Darkness", amount: WEAKNESS_BONUS },
    retreat: "Colorless x3",
    ability: { name: "Super-Duper Stoked", text: "Once during your turn, you may move a Darkness Energy from one of your benched Umamusume to your active Umamusume.", moveBenchedEnergyToActive: "darkness" },
    attacks: [{ name: "Never Give Up!", cost: { colorless: 1 }, damage: 10, damagePerAttachedEnergy: { types: ["psychic", "darkness"], amount: 10 }, text: "For every Psychic or Darkness Energy attached to this Umamusume, this attack does +10 damage." }],
  },
  riceShowerBasic: {
    id: "riceShowerBasic",
    owner: "rival",
    kind: "pokemon",
    name: "Rice Shower",
    label: "Umamusume - Dark - Basic",
    species: "Rice Shower",
    type: "Darkness",
    stage: 0,
    hp: 50,
    portrait: "/assets/umamusume/rice-shower-basic.png",
    weakness: { type: "Metal", amount: WEAKNESS_BONUS },
    retreat: "Empty",
    attacks: [{ name: "Fear", cost: { darkness: 1 }, damage: 30, text: "Do 30 damage to the active Umamusume." }],
  },
  riceShowerStage1: {
    id: "riceShowerStage1",
    owner: "rival",
    kind: "pokemon",
    name: "Rice Shower",
    label: "Umamusume - Dark - Stage 1",
    species: "Rice Shower",
    type: "Darkness",
    stage: 1,
    evolvesFrom: "Rice Shower",
    hp: 80,
    portrait: "/assets/umamusume/rice-shower-stage1.png",
    weakness: { type: "Metal", amount: WEAKNESS_BONUS },
    retreat: "Colorless",
    attacks: [{ name: "Fractured Dreams", cost: { darkness: 1 }, damage: 30, draw: 1, text: "Do 30 damage. Draw a card." }],
  },
  riceShowerStage2: {
    id: "riceShowerStage2",
    owner: "rival",
    kind: "pokemon",
    name: "Rice Shower",
    label: "Umamusume - Dark - Stage 2",
    species: "Rice Shower",
    type: "Darkness",
    stage: 2,
    evolvesFrom: "Rice Shower",
    hp: 140,
    portrait: "/assets/umamusume/rice-shower-stage2.png",
    weakness: { type: "Metal", amount: WEAKNESS_BONUS },
    retreat: "Colorless x2",
    attacks: [{ name: "Blue Rose Closer", cost: { darkness: 2 }, damage: 80, discardEnergy: { darkness: 1 }, text: "Discard one D Energy from this Umamusume." }],
  },
  tazunaHayakawa: {
    id: "tazunaHayakawa",
    kind: "trainer",
    trainerType: "supporter",
    name: "Tazuna Hayakawa",
    label: "Trainer - Supporter",
    image: "/assets/trainer/supporter/tazuna-hayakawa.png",
    text: "Draw 2 cards.",
    effect: { draw: 2 },
  },
  carrotHamburgerSteak: {
    id: "carrotHamburgerSteak",
    kind: "trainer",
    trainerType: "item",
    name: "Carrot Hamburger Steak",
    label: "Trainer - Item",
    image: "/assets/trainer/item/carrot-hamburger-steak.png",
    text: "Heal 30 damage from one of your Umamusume.",
    effect: { heal: 30, healTarget: "any" },
  },
  carrotJelly: {
    id: "carrotJelly",
    kind: "trainer",
    trainerType: "item",
    name: "Carrot Jelly",
    label: "Trainer - Item",
    image: "/assets/trainer/item/carrot-jelly.png",
    text: "During this turn, the Retreat Cost of your active Umamusume is 1 less.",
    effect: { retreatCostReduction: 1 },
  },
  makeDebutScout: {
    id: "makeDebutScout",
    kind: "trainer",
    trainerType: "item",
    name: "3★ Make Debut Scout",
    label: "Trainer - Item",
    image: "/assets/trainer/item/3★-make-debut-scout.png",
    text: "You can use this card only if you discard 1 other card from your hand. Search your deck for an Umamusume and put it into your hand.",
    effect: { discardOtherCard: true, searchPokemon: true },
  },
  traineeScoutTicket: {
    id: "traineeScoutTicket",
    kind: "trainer",
    trainerType: "item",
    name: "Trainee Scout Ticket",
    label: "Trainer - Item",
    image: "/assets/trainer/item/trainee-scout-ticket.png",
    text: "Put 1 random Basic Umamusume from your deck into your hand.",
    effect: { searchRandomBasicPokemon: true },
  },
  yayoiAkikawa: {
    id: "yayoiAkikawa",
    kind: "trainer",
    trainerType: "supporter",
    name: "Yayoi Akikawa",
    label: "Trainer - Supporter",
    image: "/assets/trainer/supporter/yayoi-akikawa.png",
    text: "Switch out your opponent's active Umamusume to the Bench. Your opponent chooses the new active Umamusume.",
    effect: { gustOpponent: true },
  },
  aoiKiryuin: {
    id: "aoiKiryuin",
    kind: "trainer",
    trainerType: "supporter",
    name: "Aoi Kiryuin",
    label: "Trainer - Supporter",
    image: "/assets/trainer/supporter/aoi-kiryuin.png",
    text: "During this turn, attacks used by your Umamusume do +10 damage to your opponent's active Umamusume.",
    effect: { attackDamageBonus: 10 },
  },
  teamCanopus: {
    id: "teamCanopus",
    kind: "trainer",
    trainerType: "supporter",
    name: "Team Canopus",
    label: "Trainer - Supporter",
    image: "/assets/trainer/supporter/team-canopus.png",
    text: "You may attach one extra Energy to your Umamusume this turn.",
    effect: { extraEnergyAttach: 1 },
  },
  nakayamaTurf: {
    id: "nakayamaTurf",
    kind: "trainer",
    trainerType: "stadium",
    name: "Nakayama Turf",
    label: "Trainer - Stadium",
    image: "/assets/trainer/stadium/nakayama-turf.png",
    text: "The Retreat Cost of each Umamusume in play is 1 Colorless less.",
    effect: { globalRetreatCostReduction: 1 },
  },
  hanshinRacetrack: {
    id: "hanshinRacetrack",
    kind: "trainer",
    trainerType: "stadium",
    name: "Hanshin Racetrack",
    label: "Trainer - Stadium",
    image: "/assets/trainer/stadium/hanshin-racetrack.png",
    text: "Each Basic Umamusume in play gets +20 HP.",
    effect: { basicHpBonus: 20 },
  },
};

export const matikanetannhauserDeckList = [
  "matikanetannhauserBasic",
  "matikanetannhauserBasic",
  "matikanetannhauserStage1",
  "matikanetannhauserStage1",
  "matikanetannhauserStage2",
  "matikanetannhauserStage2",
  "niceNatureBasic",
  "niceNatureBasic",
  "tazunaHayakawa",
  "tazunaHayakawa",
  "carrotHamburgerSteak",
  "carrotJelly",
  "makeDebutScout",
  "makeDebutScout",
  "traineeScoutTicket",
  "traineeScoutTicket",
  "teamCanopus",
  "teamCanopus",
  "nakayamaTurf",
  "hanshinRacetrack",
];

export const mihonoBourbonDeckList = [
  "mihonoBourbonBasic",
  "mihonoBourbonBasic",
  "mihonoBourbonStage1",
  "mihonoBourbonStage1",
  "mihonoBourbonStage2",
  "mihonoBourbonStage2",
  "nishinoFlowerBasic",
  "nishinoFlowerBasic",
  "tazunaHayakawa",
  "tazunaHayakawa",
  "carrotHamburgerSteak",
  "carrotHamburgerSteak",
  "carrotJelly",
  "carrotJelly",
  "makeDebutScout",
  "traineeScoutTicket",
  "teamCanopus",
  "teamCanopus",
  "nakayamaTurf",
  "hanshinRacetrack",
];

export const riceShowerDeckList = [
  "riceShowerBasic",
  "riceShowerBasic",
  "riceShowerStage1",
  "riceShowerStage1",
  "riceShowerStage2",
  "riceShowerStage2",
  "haruUraraBasic",
  "haruUraraBasic",
  "tazunaHayakawa",
  "tazunaHayakawa",
  "carrotHamburgerSteak",
  "carrotHamburgerSteak",
  "makeDebutScout",
  "makeDebutScout",
  "traineeScoutTicket",
  "traineeScoutTicket",
  "teamCanopus",
  "teamCanopus",
  "nakayamaTurf",
  "hanshinRacetrack",
];

export const premadeDecks = [
  {
    id: "matikanetannhauser",
    name: "Matikanetannhauser",
    coverCardId: "matikanetannhauserStage2",
    cardIds: matikanetannhauserDeckList,
  },
  {
    id: "riceShower",
    name: "Rice Shower",
    coverCardId: "riceShowerStage2",
    cardIds: riceShowerDeckList,
  },
  {
    id: "mihonoBourbon",
    name: "Mihono Bourbon",
    coverCardId: "mihonoBourbonStage2",
    cardIds: mihonoBourbonDeckList,
  },
];

export const defaultPlayerDeckId = "mihonoBourbon";
export const defaultRivalDeckId = "riceShower";

export const playerDeckList = premadeDecks.find((deck) => deck.id === defaultPlayerDeckId)?.cardIds ?? mihonoBourbonDeckList;
export const rivalDeckList = premadeDecks.find((deck) => deck.id === defaultRivalDeckId)?.cardIds ?? riceShowerDeckList;

export const gameData: GameData = {
  cards,
  playerDeckList,
  rivalDeckList,
};
