import type { Card, EnergyType, GameData } from "./types";

export const MAX_POINTS = 3;
export const MAX_BENCH = 3;
export const MAX_HAND = 10;
export const OPENING_HAND = 5;
export const WEAKNESS_BONUS = 20;

export const energyImages: Record<EnergyType, string> = {
  grass: "/assets/energy/grass-energy.png",
  fire: "/assets/energy/fire-energy.png",
  water: "/assets/energy/water-energy.png",
  lightning: "/assets/energy/lightning-energy.png",
  psychic: "/assets/energy/psychic-energy.png",
  fighting: "/assets/energy/fighting-energy.png",
  darkness: "/assets/energy/darkness-energy.png",
  steel: "/assets/energy/steel-energy.png",
  colorless: "/assets/energy/colorless-energy.png",
  dragon: "/assets/energy/dragon-energy.png",
};

export const cards: Record<string, Card> = {
  matikanetannhauserBasic: {
    id: "matikanetannhauserBasic",
    owner: "player",
    kind: "umamusume",
    name: "Matikanetannhauser",
    label: "Umamusume - Psychic - Basic",
    species: "Matikanetannhauser",
    type: "Psychic",
    stage: 0,
    hp: 60,
    portrait: "/assets/umamusume/matikanetannhauser-basic.png",
    weakness: { type: "Darkness", amount: WEAKNESS_BONUS },
    retreat: "Colorless",
    attacks: [{ name: "Nosebleed", cost: { psychic: 1 }, damage: 20, text: "Do 20 damage to the Active Umamusume." }],
  },
  matikanetannhauserStage1: {
    id: "matikanetannhauserStage1",
    owner: "player",
    kind: "umamusume",
    name: "Matikanetannhauser",
    label: "Umamusume - Psychic - Stage 1",
    species: "Matikanetannhauser",
    type: "Psychic",
    stage: 1,
    evolvesFrom: "Matikanetannhauser",
    hp: 100,
    portrait: "/assets/umamusume/matikanetannhauser-stage1.png",
    weakness: { type: "Darkness", amount: WEAKNESS_BONUS },
    retreat: "Colorless x2",
    attacks: [{ name: "Bad Luck, Dispel!", cost: { psychic: 2 }, damage: 40, coinBonus: 20, text: "Flip a coin. If heads, this attack does +20 damage." }],
  },
  matikanetannhauserStage2: {
    id: "matikanetannhauserStage2",
    owner: "player",
    kind: "umamusume",
    name: "Matikanetannhauser",
    label: "Umamusume - Psychic - Stage 2",
    species: "Matikanetannhauser",
    type: "Psychic",
    stage: 2,
    evolvesFrom: "Matikanetannhauser",
    hp: 150,
    portrait: "/assets/umamusume/matikanetannhauser-stage2.png",
    weakness: { type: "Darkness", amount: WEAKNESS_BONUS },
    retreat: "Colorless x2",
    ability: { name: "Ei, Ei, Mun!", text: "If this Umamusume is in the Active Spot, heal 10 HP at the start of your turn.", heal: 10 },
    attacks: [{ name: "Wasshoi Mambo!", cost: { psychic: 2, colorless: 1 }, damage: 60, coinBonus: 40, text: "Flip a coin. If heads, this attack does +40 damage." }],
  },
  niceNatureBasic: {
    id: "niceNatureBasic",
    owner: "player",
    kind: "umamusume",
    name: "Nice Nature",
    label: "Umamusume - Grass - Basic",
    species: "Nice Nature",
    type: "Grass",
    stage: 0,
    hp: 70,
    portrait: "/assets/umamusume/nice-nature-basic.png",
    weakness: { type: "Fire", amount: WEAKNESS_BONUS },
    retreat: "Colorless",
    ability: { name: "Supporting Star", text: "Your Active Umamusume gets +10 HP. This Ability does not stack.", activeHpBonus: 10 },
    attacks: [{ name: "Third Again?!", cost: { grass: 1, colorless: 1 }, damage: 40, text: "Do 40 damage to the Active Umamusume." }],
  },
  nishinoFlowerBasic: {
    id: "nishinoFlowerBasic",
    owner: "player",
    kind: "umamusume",
    name: "Nishino Flower",
    label: "Umamusume - Grass - Basic",
    species: "Nishino Flower",
    type: "Grass",
    stage: 0,
    hp: 70,
    portrait: "/assets/umamusume/nishino-flower-basic.png",
    weakness: { type: "Fire", amount: WEAKNESS_BONUS },
    retreat: "Colorless",
    attacks: [{ name: "Budding Blossom", cost: { grass: 1 }, damage: 20, heal: 10, healTarget: "any", text: "Heal 10 damage from 1 of your Umamusume." }],
  },
  mihonoBourbonBasic: {
    id: "mihonoBourbonBasic",
    owner: "player",
    kind: "umamusume",
    name: "Mihono Bourbon",
    label: "Umamusume - Steel - Basic",
    species: "Mihono Bourbon",
    type: "Steel",
    stage: 0,
    hp: 50,
    portrait: "/assets/umamusume/mihono-bourbon-basic.png",
    weakness: { type: "Fighting", amount: WEAKNESS_BONUS },
    retreat: "Colorless",
    ability: { name: "Cyborg Armor", text: "This Umamusume takes 10 less damage from attacks.", damageReduction: 10 },
    attacks: [{ name: "Reflect", cost: { steel: 1 }, damage: 20, text: "Do 20 damage to the Active Umamusume." }],
  },
  mihonoBourbonStage1: {
    id: "mihonoBourbonStage1",
    owner: "player",
    kind: "umamusume",
    name: "Mihono Bourbon",
    label: "Umamusume - Steel - Stage 1",
    species: "Mihono Bourbon",
    type: "Steel",
    stage: 1,
    evolvesFrom: "Mihono Bourbon",
    hp: 90,
    portrait: "/assets/umamusume/mihono-bourbon-stage1.png",
    weakness: { type: "Fighting", amount: WEAKNESS_BONUS },
    retreat: "Colorless x2",
    ability: { name: "Cyborg Armor", text: "This Umamusume takes 10 less damage from attacks.", damageReduction: 10 },
    attacks: [{ name: "Mirror Shot", cost: { steel: 1, colorless: 1 }, damage: 40, bonusIfTookDamageLastTurn: 10, text: "If this Umamusume took damage last turn, this attack does +10 damage." }],
  },
  mihonoBourbonStage2: {
    id: "mihonoBourbonStage2",
    owner: "player",
    kind: "umamusume",
    name: "Mihono Bourbon",
    label: "Umamusume - Steel - Stage 2",
    species: "Mihono Bourbon",
    type: "Steel",
    stage: 2,
    evolvesFrom: "Mihono Bourbon",
    hp: 140,
    portrait: "/assets/umamusume/mihono-bourbon-stage2.png",
    weakness: { type: "Fighting", amount: WEAKNESS_BONUS },
    retreat: "Colorless x3",
    ability: { name: "Cyborg Armor", text: "This Umamusume takes 10 less damage from attacks.", damageReduction: 10 },
    attacks: [{ name: "G00 1st. F∞", cost: { steel: 2, colorless: 1 }, damage: 60, bonusIfTookDamageLastTurn: 20, text: "If this Umamusume took damage last turn, this attack does +20 damage." }],
  },
  haruUraraBasic: {
    id: "haruUraraBasic",
    owner: "player",
    kind: "umamusume",
    name: "Haru Urara",
    label: "Umamusume - Psychic - Basic",
    species: "Haru Urara",
    type: "Psychic",
    stage: 0,
    hp: 90,
    portrait: "/assets/umamusume/haru-urara-basic.png",
    weakness: { type: "Darkness", amount: WEAKNESS_BONUS },
    retreat: "Colorless x3",
    ability: { name: "Super-Duper Stoked", text: "Once during your turn, you may move 1 Psychic or Darkness Energy from 1 of your Benched Umamusume to your Active Umamusume. You cannot use more than 1 Super-Duper Stoked Ability during your turn.", moveBenchedEnergyToActive: ["psychic", "darkness"] },
    attacks: [{ name: "Never Give Up!", cost: { colorless: 1 }, damage: 10, damagePerAttachedEnergy: { types: ["psychic", "darkness"], amount: 10 }, text: "For every Psychic or Darkness Energy attached to this Umamusume, this attack does +10 damage." }],
  },
  agnesDigitalBasic: {
    id: "agnesDigitalBasic",
    owner: "player",
    kind: "umamusume",
    name: "Agnes Digital",
    label: "Umamusume - Fire - Basic",
    species: "Agnes Digital",
    type: "Fire",
    stage: 0,
    hp: 60,
    portrait: "/assets/umamusume/agnes-digital-basic.png",
    weakness: { type: "Water", amount: WEAKNESS_BONUS },
    retreat: "Colorless",
    attacks: [{ name: "Fangirling", cost: { fire: 1 }, damage: 0, damagePerUmamusumeInPlay: { side: "own", amount: 10 }, text: "This attack does 10 damage for each of your Umamusume in play." }],
  },
  agnesDigitalStage1: {
    id: "agnesDigitalStage1",
    owner: "player",
    kind: "umamusume",
    name: "Agnes Digital",
    label: "Umamusume - Fire - Stage 1",
    species: "Agnes Digital",
    type: "Fire",
    stage: 1,
    evolvesFrom: "Agnes Digital",
    hp: 100,
    portrait: "/assets/umamusume/agnes-digital-stage1.png",
    weakness: { type: "Water", amount: WEAKNESS_BONUS },
    retreat: "Colorless x2",
    ability: { name: "Burning Passion", text: "If this Umamusume has 4 or more Fire Energy attached, her attacks do +30 damage.", attackDamageBonusIfAttachedEnergy: { type: "fire", min: 4, amount: 30 } },
    attacks: [{ name: "Uma Stan", cost: { fire: 2 }, damage: 0, damagePerUmamusumeInPlay: { side: "all", amount: 10 }, text: "This attack does 10 damage for each Umamusume in play." }],
  },
  agnesTachyonBasic: {
    id: "agnesTachyonBasic",
    owner: "player",
    kind: "umamusume",
    name: "Agnes Tachyon",
    label: "Umamusume - Fire - Basic",
    species: "Agnes Tachyon",
    type: "Fire",
    stage: 0,
    hp: 60,
    portrait: "/assets/umamusume/agnes-tachyon-basic.png",
    weakness: { type: "Water", amount: WEAKNESS_BONUS },
    retreat: "Colorless",
    attacks: [{ name: "Data Sampling", cost: { colorless: 1 }, damage: 0, draw: 1, text: "Draw 1 card." }],
  },
  agnesTachyonStage1: {
    id: "agnesTachyonStage1",
    owner: "player",
    kind: "umamusume",
    name: "Agnes Tachyon",
    label: "Umamusume - Fire - Stage 1",
    species: "Agnes Tachyon",
    type: "Fire",
    stage: 1,
    evolvesFrom: "Agnes Tachyon",
    hp: 90,
    portrait: "/assets/umamusume/agnes-tachyon-stage1.png",
    weakness: { type: "Water", amount: WEAKNESS_BONUS },
    retreat: "Colorless x2",
    ability: { name: "Tach-nology", text: "Once during your turn, you may discard 1 card. If you do, draw 2 cards. You cannot use more than 1 Tach-nology Ability during your turn.", discardToDraw: { discard: 1, draw: 2 } },
    attacks: [{ name: "Guinea Pig Experiment", cost: { fire: 1, colorless: 1 }, damage: 40, text: "Do 40 damage to the Active Umamusume." }],
  },
  riceShowerBasic: {
    id: "riceShowerBasic",
    owner: "opponent",
    kind: "umamusume",
    name: "Rice Shower",
    label: "Umamusume - Dark - Basic",
    species: "Rice Shower",
    type: "Darkness",
    stage: 0,
    hp: 50,
    portrait: "/assets/umamusume/rice-shower-basic.png",
    weakness: { type: "Steel", amount: WEAKNESS_BONUS },
    retreat: "Empty",
    attacks: [{ name: "Fear", cost: { darkness: 1 }, damage: 30, text: "Do 30 damage to the Active Umamusume." }],
  },
  riceShowerStage1: {
    id: "riceShowerStage1",
    owner: "opponent",
    kind: "umamusume",
    name: "Rice Shower",
    label: "Umamusume - Dark - Stage 1",
    species: "Rice Shower",
    type: "Darkness",
    stage: 1,
    evolvesFrom: "Rice Shower",
    hp: 80,
    portrait: "/assets/umamusume/rice-shower-stage1.png",
    weakness: { type: "Steel", amount: WEAKNESS_BONUS },
    retreat: "Colorless",
    attacks: [{ name: "Fractured Dreams", cost: { darkness: 1 }, damage: 30, draw: 1, text: "Do 30 damage. Draw 1 card." }],
  },
  riceShowerStage2: {
    id: "riceShowerStage2",
    owner: "opponent",
    kind: "umamusume",
    name: "Rice Shower",
    label: "Umamusume - Dark - Stage 2",
    species: "Rice Shower",
    type: "Darkness",
    stage: 2,
    evolvesFrom: "Rice Shower",
    hp: 140,
    portrait: "/assets/umamusume/rice-shower-stage2.png",
    weakness: { type: "Steel", amount: WEAKNESS_BONUS },
    retreat: "Colorless x2",
    attacks: [{ name: "Blue Rose Closer", cost: { darkness: 2 }, damage: 80, discardEnergy: { darkness: 1 }, text: "Discard 1 Darkness Energy from this Umamusume." }],
  },
  tazunaHayakawa: {
    id: "tazunaHayakawa",
    kind: "trainer",
    trainerType: "supporter",
    name: "Tazuna Hayakawa",
    label: "Trainer - Supporter",
    image: "/assets/trainer/supporter/tazuna-hayakawa.png",
    text: "Draw 2 cards.",
    effect: { draw: 2 },
  },
  carrotHamburgerSteak: {
    id: "carrotHamburgerSteak",
    kind: "trainer",
    trainerType: "item",
    name: "Carrot Hamburger Steak",
    label: "Trainer - Item",
    image: "/assets/trainer/item/carrot-hamburger-steak.png",
    text: "Heal 20 damage from 1 of your Umamusume.",
    effect: { heal: 20, healTarget: "any" },
  },
  carrotJelly: {
    id: "carrotJelly",
    kind: "trainer",
    trainerType: "item",
    name: "Carrot Jelly",
    label: "Trainer - Item",
    image: "/assets/trainer/item/carrot-jelly.png",
    text: "During this turn, the Retreat Cost of your active Umamusume is 1 Colorless less.",
    effect: { retreatCostReduction: 1 },
  },
  makeDebutScout: {
    id: "makeDebutScout",
    kind: "trainer",
    trainerType: "item",
    name: "3★ Make Debut Scout",
    label: "Trainer - Item",
    image: "/assets/trainer/item/3★-make-debut-scout.png",
    text: "You can use this card only if you discard 1 other card from your hand. Search your deck for an Umamusume and put her into your hand.",
    effect: { discardOtherCard: true, searchUmamusume: true },
  },
  traineeScoutTicket: {
    id: "traineeScoutTicket",
    kind: "trainer",
    trainerType: "item",
    name: "Trainee Scout Ticket",
    label: "Trainer - Item",
    image: "/assets/trainer/item/trainee-scout-ticket.png",
    text: "Put 1 random Basic Umamusume from your deck into your hand.",
    effect: { searchRandomBasicUmamusume: true },
  },
  rainbowUncapCrystal: {
    id: "rainbowUncapCrystal",
    kind: "trainer",
    trainerType: "item",
    name: "Rainbow Uncap Crystal",
    label: "Trainer - Item",
    image: "/assets/trainer/item/rainbow-uncap-crystal.png",
    text: "Choose 1 of your Basic Umamusume in play. If you have a Stage 2 card in your hand that evolves from that Umamusume, put that card onto the Basic Umamusume to evolve it, skipping the Stage 1. You cannot use this card during your first turn or on a Basic Umamusume that was put into play this turn.",
    effect: { rainbowUncapCrystal: true },
  },
  trainingHelmet: {
    id: "trainingHelmet",
    kind: "trainer",
    trainerType: "tool",
    name: "Training Helmet",
    label: "Trainer - Tool",
    image: "/assets/trainer/tool/training-helmet.png",
    text: "The Umamusume this card is attached to takes 10 less damage.",
    effect: { toolDamageReduction: 10 },
  },
  boxingGloves: {
    id: "boxingGloves",
    kind: "trainer",
    trainerType: "tool",
    name: "Boxing Gloves",
    label: "Trainer - Tool",
    image: "/assets/trainer/tool/boxing-gloves.png",
    text: "If the Umamusume this card is attached to is in the Active Spot and is damaged by an attack from your opponent's Umamusume, do 20 damage to the Attacking Umamusume.",
    effect: { toolCounterDamage: 20 },
  },
  yayoiAkikawa: {
    id: "yayoiAkikawa",
    kind: "trainer",
    trainerType: "supporter",
    name: "Yayoi Akikawa",
    label: "Trainer - Supporter",
    image: "/assets/trainer/supporter/yayoi-akikawa.png",
    text: "Switch out your opponent's Active Umamusume to the Bench. (Your opponent chooses the new Active Umamusume.)",
    effect: { gustOpponent: true },
  },
  aoiKiryuin: {
    id: "aoiKiryuin",
    kind: "trainer",
    trainerType: "supporter",
    name: "Aoi Kiryuin",
    label: "Trainer - Supporter",
    image: "/assets/trainer/supporter/aoi-kiryuin.png",
    text: "During this turn, attacks used by your Active Umamusume do +10 damage to your opponent's Active Umamusume.",
    effect: { activeAttackDamageBonus: 10 },
  },
  teamCanopus: {
    id: "teamCanopus",
    kind: "trainer",
    trainerType: "supporter",
    name: "Team Canopus",
    label: "Trainer - Supporter",
    image: "/assets/trainer/supporter/team-canopus.png",
    text: "Generate 1 random Energy in your Energy Zone and attach it to 1 of your Benched Umamusume.",
    effect: { attachEnergyFromZoneToBench: 1 },
  },
  etsukoOtonashi: {
    id: "etsukoOtonashi",
    kind: "trainer",
    trainerType: "supporter",
    name: "Etsuko Otonashi",
    label: "Trainer - Supporter",
    image: "/assets/trainer/supporter/etsuko-otonashi.png",
    text: "Put 1 random Basic Umamusume from your discard pile into your hand.",
    effect: { randomBasicUmamusumeFromDiscard: true },
  },
  nakayamaTurf: {
    id: "nakayamaTurf",
    kind: "trainer",
    trainerType: "stadium",
    name: "Nakayama Turf",
    label: "Trainer - Stadium",
    image: "/assets/trainer/stadium/nakayama-turf.png",
    text: "The Retreat Cost of each Umamusume in play (both yours and your opponent's) is 1 Colorless less.",
    effect: { globalRetreatCostReduction: 1 },
  },
  hanshinRacetrack: {
    id: "hanshinRacetrack",
    kind: "trainer",
    trainerType: "stadium",
    name: "Hanshin Racetrack",
    label: "Trainer - Stadium",
    image: "/assets/trainer/stadium/hanshin-racetrack.png",
    text: "Each Basic Umamusume in play (both yours and your opponent's) gets +20 HP.",
    effect: { basicHpBonus: 20 },
  },
  tracenAcademy: {
    id: "tracenAcademy",
    kind: "trainer",
    trainerType: "stadium",
    name: "Tracen Academy",
    label: "Trainer - Stadium",
    image: "/assets/trainer/stadium/tracen-academy.png",
    text: "Once during each player's turn, that player may shuffle their hand into their deck and draw 4 cards. If they do, their turn ends.",
    effect: { shuffleHandIntoDeckDraw: 4 },
  },
  tracenGym: {
    id: "tracenGym",
    kind: "trainer",
    trainerType: "stadium",
    name: "Tracen Gym",
    label: "Trainer - Stadium",
    image: "/assets/trainer/stadium/tracen-gym.png",
    text: "Umamusume Tools attached to each Umamusume (both yours and your opponent's) have no effect.",
    effect: { disableTools: true },
  },
};

export const matikanetannhauserDeckList = [
  "matikanetannhauserBasic",
  "matikanetannhauserBasic",
  "matikanetannhauserStage1",
  "matikanetannhauserStage2",
  "matikanetannhauserStage2",
  "niceNatureBasic",
  "niceNatureBasic",
  "tazunaHayakawa",
  "tazunaHayakawa",
  "rainbowUncapCrystal",
  "carrotHamburgerSteak",
  "carrotJelly",
  "boxingGloves",
  "makeDebutScout",
  "makeDebutScout",
  "traineeScoutTicket",
  "teamCanopus",
  "teamCanopus",
  "nakayamaTurf",
  "hanshinRacetrack",
];

export const mihonoBourbonDeckList = [
  "mihonoBourbonBasic",
  "mihonoBourbonBasic",
  "mihonoBourbonStage1",
  "mihonoBourbonStage2",
  "mihonoBourbonStage2",
  "nishinoFlowerBasic",
  "aoiKiryuin",
  "tazunaHayakawa",
  "tazunaHayakawa",
  "carrotHamburgerSteak",
  "rainbowUncapCrystal",
  "carrotJelly",
  "boxingGloves",
  "makeDebutScout",
  "traineeScoutTicket",
  "traineeScoutTicket",
  "teamCanopus",
  "teamCanopus",
  "nakayamaTurf",
  "hanshinRacetrack",
];

export const agnesDigitalDeckList = [
  "agnesDigitalBasic",
  "agnesDigitalBasic",
  "agnesDigitalStage1",
  "agnesDigitalStage1",
  "agnesTachyonBasic",
  "agnesTachyonBasic",
  "agnesTachyonStage1",
  "agnesTachyonStage1",
  "tazunaHayakawa",
  "etsukoOtonashi",
  "carrotHamburgerSteak",
  "carrotJelly",
  "traineeScoutTicket",
  "traineeScoutTicket",
  "teamCanopus",
  "teamCanopus",
  "aoiKiryuin",
  "yayoiAkikawa",
  "tracenGym",
  "nakayamaTurf",
];

export const riceShowerDeckList = [
  "riceShowerBasic",
  "riceShowerBasic",
  "riceShowerStage1",
  "riceShowerStage2",
  "riceShowerStage2",
  "haruUraraBasic",
  "haruUraraBasic",
  "tazunaHayakawa",
  "tazunaHayakawa",
  "yayoiAkikawa",
  "carrotHamburgerSteak",
  "rainbowUncapCrystal",
  "trainingHelmet",
  "makeDebutScout",
  "makeDebutScout",
  "traineeScoutTicket",
  "teamCanopus",
  "teamCanopus",
  "tracenAcademy",
  "hanshinRacetrack",
];

export const premadeDecks = [
  {
    id: "matikanetannhauser",
    name: "Matikanetannhauser",
    coverCardId: "matikanetannhauserStage2",
    cardIds: matikanetannhauserDeckList,
  },
  {
    id: "riceShower",
    name: "Rice Shower",
    coverCardId: "riceShowerStage2",
    cardIds: riceShowerDeckList,
  },
  {
    id: "mihonoBourbon",
    name: "Mihono Bourbon",
    coverCardId: "mihonoBourbonStage2",
    cardIds: mihonoBourbonDeckList,
  },
  {
    id: "agnesDigital",
    name: "Agnes Digital",
    coverCardId: "agnesDigitalStage1",
    cardIds: agnesDigitalDeckList,
  },
];

export const defaultPlayerDeckId = "matikanetannhauser";
export const defaultOpponentDeckId = "riceShower";

export const playerDeckList = premadeDecks.find((deck) => deck.id === defaultPlayerDeckId)?.cardIds ?? mihonoBourbonDeckList;
export const opponentDeckList = premadeDecks.find((deck) => deck.id === defaultOpponentDeckId)?.cardIds ?? riceShowerDeckList;

export const gameData: GameData = {
  cards,
  playerDeckList,
  opponentDeckList,
};
